services:
  # --- SHARED INFRASTRUCTURE ---
  database:
    image: postgres:16-alpine
    ports:
      - "5434:5432" # Map [Host Port]:[Container Port]
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db # Postgres creates ONE db on startup
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

  messenger-hub:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672" # UI for the reviewer to see messages
      - "5672:5672" # Mapping this allows you to test connection from your host machine
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/rmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  cache:
    image: redis:7-alpine

  # --- MICROSERVICE: PRODUCTS ---
  products-php:
    build: .
    volumes:
      - ./service-products:/var/www/html
    depends_on:
      messenger-hub:
        condition: service_healthy # Wait for RabbitMQ to be "Healthy"

  products-web:
    image: nginx:alpine
    ports:
      - "8081:80"
    environment:
      - PHP_UPSTREAM=products-php
    volumes:
      - ./service-products:/var/www/html
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - products-php

  # --- MICROSERVICE: ORDERS ---
  orders-php:
    build: .
    volumes:
      - ./service-orders:/var/www/html
    depends_on:
      messenger-hub:
        condition: service_healthy # Wait for RabbitMQ to be "Healthy"

  orders-web:
    image: nginx:alpine
    ports:
      - "8082:80"
    environment:
      - PHP_UPSTREAM=orders-php # MUST match the service name
    volumes:
      - ./service-orders:/var/www/html
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - orders-php

volumes:
  db-data:
