services:
  # --- SHARED INFRASTRUCTURE ---
  database:
    image: postgres:16-alpine
    ports:
      - "5434:5432" # Map [Host Port]:[Container Port]
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db # Postgres creates ONE db on startup
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

  messenger-hub:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672" # UI for the reviewer to see messages

  cache:
    image: redis:7-alpine

  # --- MICROSERVICE: PRODUCTS ---
  products-php:
    build: .
    volumes:
      - ./service-products:/var/www/html
    environment:
      # Use the correct user (symfony) and the DB you want to create/use
      DATABASE_URL: "postgresql://symfony:password@database:5432/products_db?serverVersion=16.0.0"
      DEFAULT_URI: "http://localhost:8081" # Matches products-web port
      APP_ENV: dev
      POSTGRES_VERSION: "16.0.0"
      APP_SECRET: some_secret_string

  products-web:
    image: nginx:alpine
    ports:
      - "8081:80"
    environment:
      - PHP_UPSTREAM=products-php
    volumes:
      - ./service-products:/var/www/html
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - products-php

  # --- MICROSERVICE: ORDERS ---
  orders-php:
    build: .
    volumes:
      - ./service-orders:/var/www/html
    environment:
      DATABASE_URL: "postgresql://symfony:password@database:5432/orders_db"
      POSTGRES_VERSION: "16.0.0"
      DEFAULT_URI: "http://localhost:8082" # Matches orders-web port
      APP_ENV: dev
      APP_SECRET: some_secret_string

  orders-web:
    image: nginx:alpine
    ports:
      - "8082:80"
    environment:
      - PHP_UPSTREAM=orders-php # MUST match the service name below
    volumes:
      - ./service-orders:/var/www/html
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - orders-php

volumes:
  db-data:
